# fly.toml app configuration file generated for frontend-thrumming-voice-5200 on 2025-07-13T15:00:36+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-thrumming-voice-5200'
primary_region = 'fra'

[build.args]
  NEXT_PUBLIC_API = 'https://backend-summer-field-1711.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
