services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://0.0.0.0:3000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API=http://0.0.0.0:8081
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
